# Build react
#FROM node:20-alpine3.20 AS vite-app

#WORKDIR /usr/src/app

#COPY client/package*.json client/package-lock.json ./

#RUN npm ci

#COPY ./client ./

#RUN npm run build

#FROM nginx:alpine

#WORKDIR /

#COPY ../nginx /etc/nginx/conf.d
#COPY --from=vite-app ./usr/src/app/dist /usr/share/nginx/html

#CMD ["nginx", "-g", "daemon off;"]

FROM node:alpine

WORKDIR /usr/src/app

COPY . .

RUN npm install

EXPOSE 5173
